project:
  type: website
  output-dir: _site

bibliography: "bib/publications.bib"
csl: "bib/chicago-author-date.csl"

website:
  title: "R. Abraham Holland"
  image: "files/RAH_Profile_Photo.jpg"
  site-url: "https://abrahamholland.github.io/my-website"
  description: "Brief description or tagline"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Publications"
        file: pubs.qmd
      - text: "Presentations"
        file: presentations.qmd
      - text: "CV"
        file: cv.qmd
  page-footer:
    left: "© 2025 R. Abraham Holland"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true


