---
title: "Publications"
---

## Policy Publications
Bewley, Jennifer L., Ayeisha A. Brinson, R. Abraham Holland, Anusuya Sivaram, Roxana Leal, John E. Sabatini, Kelsey R. Stanley, and Katherine C. S. Ross. “Independent Evaluation of the National Oceanic and Atmospheric Administration’s National Weather Service Tornado Forecasting and Warning Services.” IDA Product 3002824, Alexandria, VA, May 2025.
<details>
<summary><strong>Abstract</strong></summary>
This independent study assesses the performance and operational effectiveness of the National Weather Service's (NWS) tornado forecasting and warning services in light of the mandates in the 2017 Weather Research and Forecasting Innovation Act. We examine the extent to which the National Oceanic and Atmospheric Administration (NOAA) has achieved Tornado Warning Improvement and Extension Program (TWIEP) objectives, which aim to minimize loss of life and economic damage from tornadoes through enhanced forecast accuracy and lead time.

The analysis finds that although the NWS consistently met its false alarm ratio (FAR) performance targets over the past decade, it underperformed in key areas such as probability of detection (POD) and warning lead time. In addition, NOAA has not established clear outcome metrics to evaluate its progress toward TWIEP goals, and deficiencies exist in both the planning and implementation of tornado-related research and communication strategies. The report identifies gaps in NOAA’s operational integration of research outcomes (R2O and R2A processes), absence of evaluations for risk communication effectiveness, and inconsistencies in the public presentation of official lead-time metrics.

The report offers six recommendations to enhance NWS effectiveness, including the development of a detailed TWIEP implementation plan, formulation of loss-related performance metrics, and improved post-implementation evaluation of research. It also calls for reassessment of lead-time metrics and their communication. NOAA concurred with five recommendations and partially concurred with one, citing methodological and resource challenges in establishing life and economic loss metrics. The evaluation underscores the need for a coordinated, evidence-based framework to bolster public trust and operational accountability in NOAA's tornado warning systems.

[Full Paper](https://www.ida.org/research-and-publications/publications/all/i/in/independent-evaluation-of-the-noaa-national-weather-service-tornado-forecasting-and-warning-services) 

Media Coverage: [E&E News](https://www.dropbox.com/scl/fi/feopzbryrmimbg1v5lhh0/NWS_failing_to_meet_tornado_warning_standards__IG_finds_-_EENEWS.pdf?rlkey=4l3y96jcm3f93cs73374hlwjt&st=vpsj62ot&dl=0)

<!--
https://www.dropbox.com/scl/fi/ez6s75yb4xkuai5rbdq4d/OIG-25-026-I_FinalReport-SECURED.pdf?rlkey=oqxtgtn67kil14xamw3wc5ylt&e=1&st=ke6jrq4m&dl=0
-->
</details>


Holland, R. Abraham, Jennifer L. Bewley, Joseph F. Adams, Ayeisha A. Brinson, Olivia Gozdz, John C. Maxwell, III, and Ashley Nunes. “Adapting Department of Defense Training Based on a Changing Climate in the Arctic.” IDA Product 3003625, Alexandria, VA, December 2, 2024. 
<details>
<summary><strong>Abstract</strong></summary>
This study identified potential impacts on the Department of Defense (DoD) training enterprise driven by projected changes in the Arctic by 2050. The Institute for Defense Analyses’ approach emphasized combining existing climate models with established military doctrine. We also focused on two specific areas of interest: off-road mobility and Alaskan wildfires. In terms of off-road mobility, we used the European High North as a case study. Projected changes in summer precipitation patterns and soil moisture result in off-road mobility improvements near the Russian-Finnish border, and deterioration in nearby Norwegian and Swedish regions. Operationally, these trends indicate greater off-road flexibility in border regions, while potential overland logistics support areas experience greater reliance on existing road networks and increased risk of airhead congestion (reduced off-road mobility in the areas near existing airfields). Therefore, combining data collection with summer training exercises that have off-road mobility requirements may yield additional value in preparing for future operating conditions.

Alaskan wildfire trends may also have operational implications, with research pointing to increases in wildfire frequency and severity. There is also no indication that the wildfire management investments required to reverse trends back to historic levels are forthcoming. As a consequence, research that models resource demand as a function of wildfire intensity, severity, and proximity to DoD equities may be valuable to the DoD training enterprise. We are aware of no research that combines climate projections with wildfire-driven demand for DoD manpower or materiel—demand that could divert resources away from regular operations and training activities and limit access to training ranges as wildfires. Increasing wildfire risks may require greater reliance on virtual and constructive training. To the extent that virtual and constructive methods are realistic to accomplish mission essential tasks and available for military organizations training in the Arctic, this may be a viable adaptation in response to increasing wildfire activity.

Full paper classified CUI//NOFORN.
</details>

Holland, R. Abraham, Jennifer L. Bewley, Joseph F. Adams, Astrid I. Berge, Shane Gillies, Caroline R. Earle, John C. Maxwell, III, and Sara C. Runkel. “Adapting Department of Defense Training Based on a Changing Climate.” IDA Document D-33459, Alexandria, VA, February 1, 2024. 
<details>
<summary><strong>Abstract</strong></summary>
This study aimed to identify Department of Defense (DoD) training gaps driven by a changing climate. IDA’s approach emphasized using existing climate models and established military doctrine to project how climate change will affect selected DoD operations, equipment, and training. Our analysis used the U.S. Marine Corps III Marine Expeditionary Force 31st Marine Expeditionary Unit (31st MEU) as a case study; it indicated live exercise coverage gaps across the range of current and expected future environmental conditions. We also identified additional operational implications for the 31st MEU’s ability to conduct amphibious operations in an important training location (Luzon, Philippines) by 2050. All of the analyses conducted in this project can be replicated and extended to other climate hazards, geographic regions, or unit types.

Full paper classified CUI//Distribution Statement E: Distribution authorized to DoD Components only.
</details>

Kirk, Hannah L., Jennifer L. Bewley, Ayeisha A. Brinson, and R. Abraham Holland. “Navigating the Greenhouse Gas Accounting Regulatory Environment for Federal Contractors and the Department of Defense.” IDA Product 3000771, Alexandria, VA, February 1, 2024. 
<details>
<summary><strong>Abstract</strong></summary>
Recent presidential executive orders have mandated federal agencies, including the Department of Defense, to disclose and reduce their own greenhouse gas (GHG) emissions, and to reduce emissions through the procurement process by including reporting requirements for federal contractors. In November 2022, federal agencies began the rulemaking process to amend the Federal Acquisition Regulation. The proposed change would require significant contractors to use existing, non-governmental standards in their GHG disclosures. This paper outlines key terms, standards, and issues associated with GHG accounting and reporting, as well as identified areas for further research. 

[Full Paper](https://idalink.org/3000771-LP)
</details>

Earle, Caroline R., Amy A. Alrich, R. Abraham Holland, Nigel J. Mease, Neil V. Mithal, EunRae Oh, and Christina M. Patterson. “An Analysis of Alternatives for Subterranean Training Facilities.” IDA Product 3000608, Alexandria, VA, October 2, 2023. 
<details>
<summary><strong>Abstract</strong></summary>
An Analysis of Alternatives study on subterranean (SbT) training facilities to inform DOD program and budget decisions to establish an enduring joint training venue that replicates “deep” Category Three (Cat 3) underground military facilities, in order to support Joint interoperable training and full-scale mission rehearsals to address growing SbT threats.

Full paper classified SECRET//FGI KOR//NOFORN.
</details>

Holland, R. Abraham, Matthew S. Goldberg, John C. Maxwell, III, and Kelsey R. Stanley. “Don't Bug Me: Climate Change, Pathogenic Disease, and Operational Military Medicine.” IDA Product 3000293, Alexandria, VA, September 1, 2023.
<details>
<summary><strong>Abstract</strong></summary>
The Department of Defense (DoD) has developed several taxonomies of ‘important’ medical conditions with regard to (1) planning for military medical research investments; (2) planning for medical care delivered in the wartime theater; and (3) anticipating medical conditions requiring evacuation from the theater. The civilian scientific literature contains many examples of medical conditions for which incidence may change in light of a variety of climatic trends. This paper links that civilian literature to each of the DoD taxonomies to determine how operational military medicine might be affected by a changing climate.
</details>

Holland, R. Abraham, Sophie P. Bass, Sarah K. John, and Jamie M. Lindly. “Key Empirical Trends in the Military Health System Since the COVID-19 Pandemic.” IDA Product 3000292, Alexandria, VA, September 1, 2023.
<details>
<summary><strong>Abstract</strong></summary>
The interdependencies of purchased and direct care available to MHS beneficiaries was never more pronounced than during the pandemic. This paper examines care shifts in outpatient, inpatient, and cost across purchased and direct care delivery sources before and after the COVID-19 pandemic. The paper concludes by considering the implications of the shifts observed on future cost growth and medical force readiness challenges to the department.
</details>

Holland, R. Abraham, Cullen A. Roberts, John C. Maxwell, III, and Na'im G. Kalantar. “Medical Personnel Recruitment and Retention Trends Since the COVID-19 Pandemic.” IDA Product 3000294, Alexandria, VA, September 1, 2023.
<details>
<summary><strong>Abstract</strong></summary>
We document historical trends in active component medical personnel inventory; in addition, we provide if-trends-continue projections of medical personnel inventory, discussing potential implications. To better focus on problem areas, we split analyses into subgroups defined by personnel class, Service, and seniority. These analyses indicate that medical personnel shortfalls are concentrated in the enlisted personnel and are driven by accession shortfalls; findings for medical personnel closely mirror those for personnel across all occupations. Projections indicate that personnel inventory is unlikely to recover for several years even with a rapid improvement in the recruiting market. This problem is more acute for the Army. Projections also indicate that enlisted shortfalls will impact senior enlisted end strength later in the decade.
</details>

Hallex, Matthew A., Jennifer L. Bewley, David T. Chappell, Elena de La Rosa Blanco, Shane Gillies, R. Abraham Holland, and Darlene P. Jackson. “Climate Change and Future Space Operations.” IDA Product 3000651, Alexandria, VA, March 1, 2023.
<details>
<summary><strong>Abstract</strong></summary>
This study explores the implications of climate change for space policy and other national security space equities including risks to DoD space missions, constraints on space operations form future climate policy, and new missions that could be addressed as part of DoD’s response to climate change. The study identifies the principal risks climate change poses to space operations as hazards to installations and infrastructure. The study identifies a high degree of scientific and technical uncertainty that will likely constrain domestic and international climate policy applying to space in the near-term. The study also identifies opportunities to engage with interagency and international partners on climate topics that could also be leveraged to build support for other DoD space policy equities.
</details>

Tate, David M., R. Abraham Holland, Gary R. Bliss, Matthew Breen, Patricia F. Bronson, Daniel L. Cuda, Gregory A. Davis et al. “Cost Estimate Growth and Cost Growth in NNSA Capital Acquisition Projects.” IDA Paper P-33382, Alexandria, VA, March 1, 2023.
<details>
<summary><strong>Abstract</strong></summary>
IDA was asked to perform an independent review of National Nuclear Security Administration (NNSA) capital acquisition project costs and early-stage cost estimation. IDA’s methodology included examining historical project estimates and outcomes, comparing NNSA policy and practices with those of peer organizations, and performing a root cause analysis of the High Explosive Synthesis, Formulation, and Production project. These examinations yielded a number of high-level findings, which ranged across the entire capital acquisition lifecycle, related to areas of strength and areas in need of improvement. On the basis of these findings, IDA identified actionable planning, programming, budgeting, and evaluation process improvements across the project lifecycle. IDA recommends that NNSA reconsider how Critical Decision Zero estimates are used internally, as well as the degree to which these estimates are made visible outside of the agency. Further, IDA recommends that NNSA establish and enforce reliable cost estimation practices across and within each lifecycle phase in order to support more comprehensive, well-documented, and accurate estimates. IDA has provided a detailed set of specific implementation recommendations in the main body and appendices of this analysis.

Full paper dissemination only as directed by the NNSA Office of Management and Budget DOE authority.
</details>


Holland, R. Abraham, Margaret M. Barber, Astrid I. Berge, Davis Jon M, Jacqueline L. Du Bois, Pritha Ghosh, Sarah K. John et al. “NDAA-21 Section 731 Element Review: External Observations and Implications.” IDA Document D-22741, Alexandria, VA, April 1, 2022. 
<details>
<summary><strong>Abstract</strong></summary>
This analysis by the Institute for Defense Analyses (IDA) supports a broader study required by Section 731 of the National Defense Authorization Act for Fiscal Year 2021. We conducted an independent assessment of pandemic-inspired trends outside the Military Health System (MHS) across 11 congressionally mandated focus areas. The IDA team identified 30 potential implications of civilian trends for the MHS through reviewing news reports, academic publications, public policies, and empirical data sources. When viewing all 30 potential implications as a whole, 3 common themes emerged. First, the rapid adoption of telehealth has affected health care far beyond how it is delivered. Second, the coronavirus disease 2019 (COVID-19) pandemic has also been a shock to institutions’ needs for data and rapid decision-making. Third, the MHS has a unique combination of global scope and integration. As a consequence, the MHS may be exposed to unique risks, compensate for civilian weaknesses, or benefit from disruptions within the civilian healthcare system caused by the COVID-19 pandemic. Further study of the 30 potential implications, or a more focused and comprehensive analysis of these 3 common themes, may help MHS leadership navigate this period of incredible change and challenge brought by the COVID-19 pandemic.

Full paper classified Distribution D: Distribution authorized to U.S. Government agencies and their contractors.
</details>

Hirt, Robert D, et al. “Veterans Affairs Electronic Health Record Modernization Quality Assurance Review.” IDA Paper P-20458, Alexandria, VA, February 1, 2021.
<details>
<summary><strong>Abstract</strong></summary>
In March 2020, the Department of Veterans Affairs (VA) Office of Enterprise Integration (OEI) asked the Institute for Defense Analyses (IDA), on behalf of the VA Deputy Secretary, to provide the first quality assurance review (QAR) of the Electronic Health Record modernization (EHRM) program. The goals of the QAR were to (1) provide an external, independent technical and managerial assessment, and (2) assess both government and contractor processes related to the VA’s EHRM program. The Deputy Secretary accepted all seven IDA recommendations from the baseline assessment. The level of the recommendations varied from enterprise-level recommendations regarding governance, creating enterprise goals for the program, and stakeholder engagement to program-level recommendations involving schedule and risk management. In this report, the IDA team documents its assessment across five focus areas: Leadership and Governance, Planning and Evaluation, Change Management, Data and Accessibility, and Contract Management.

Full paper dissemination only as directed by the Department of Veterans Affairs, Office of Enterprise Integration.
</details>

Adams, Joseph F, et al. “Analysis of a Salary-Based Pay System for the Quadrennial Review of Military Compensation.” IDA Document D-13204, Alexandria, VA, September 1, 2020.
<details>
<summary><strong>Abstract</strong></summary>
This paper supports the goal of the Quadrennial Review of Military Compensation (QRMC) of understanding how a compensation system that combines basic pay, housing, and subsistence allowances into a single taxable “salary” would affect Service members’ earnings and behavior. This paper also considers the readiness, cost, and tax-revenue implications of such a system. We undertook three lines of effort. First, we modeled the after-tax income effects of transitioning to a salary system. We found that any salary system that maintains constant Federal Government costs will reduce Service members’ aggregate after-tax income. Second, we used econometric models to estimate the likely responses of Service members to changes in after-tax income. We found no significant effect of state military tax exemptions on retention, suggesting that other factors are more influential than raw compensation changes. Third, we conducted focus groups with 740 Service members in every Service by visiting Active and Reserve Component installations in four states. Service members generally expressed strong skepticism of major restructuring of military compensation systems; they view the current system as imperfect, but “fair enough.” Finally, we discuss other possible mechanisms—short of adopting a salary system—that could improve the efficiency and fairness of the current system.

[Full Paper](https://www.dropbox.com/scl/fi/5knhai5ba3slf0vbpdo0b/D-13204.pdf?rlkey=pbknga15jechvj3dmdrd1u155&st=8udw6f5g&dl=0)
</details>

Huff, Nancy M., Alexander A. Armbruster, R. Abraham Holland, and Timothy J. Wojtecki. “Training Days and Retention in the Army National Guard.” IDA Paper P-13133, Alexandria, VA, May 1, 2020. 
<details>
<summary><strong>Abstract</strong></summary>
As the Army National Guard (ARNG) has become increasingly more operational, concern has grown that increasing training requirements could cause retention challenges, particularly in the wake of recommendations from the National Commission on the Future of the Army in 2016 that ARNG units be integrated even more into the operational force structure. In this paper, we investigate the effect of the requirements for a more operational ARNG by answering two sets of questions: (1) What have the training requirements been recently for ARNG units and individual soldiers and to what extent are these training requirements projected to increase in the next five years? (2) What effect does increasing training requirements have on retention? We find that programmed unit training levels are not projected to rise beyond recent historical averages through fiscal year 2023. Using an instrumental variables methodology, we estimate only modest effects of training days on retention. We estimate the largest negative effects for Brigade Combat Teams (BCTs) where each additional training day per year reduces one-year retention by an estimated 0.63 percentage points—or about 75 personnel out of 5,978 exiting within one year in response to a two-day increase in average training requirements for all BCT units.

Full paper classified CUI//Distribution E: Distribution authorized to DoD Components only.
</details>

## Academic Publications
Ashraf, Nava, Edward Glaeser, Abraham Holland, and Bryce Millett Steinberg. (2021).  
*Water, Health and Wealth: The Impact of Piped Water Outages on Disease Prevalence and Financial Transactions in Zambia.* _Economica, 88_(351), 755–781. [https://doi.org/10.1111/ecca.12369](https://doi.org/10.1111/ecca.12369)
<details>
<summary><strong>Abstract</strong></summary>
Providing clean water requires maintenance, as well as the initial connections that are typically measured. Frequently, the water supply fails in the developing world, especially when users do not pay the marginal cost of water. This paper uses the timing of frequent, unexpected water service outages in Lusaka, Zambia to identify the short-term impacts of piped water access on contagious disease, economic activity and time use. We use microdata from the primary water utility in the city on the timing and location of supply complaints to identify outages, matched to extensive administrative data across the city. Conditional on fixed effects for time and water service district within Lusaka, we find that increases in outages are associated with increased incidence of diarrhoeal disease, upper respiratory infections, typhoid fever and measles. We match outages to geolocated microdata on financial transactions from the largest mobile money provider in Zambia, and find that outages cause a reduction in financial transactions. Outages also increase the time that young girls spend at their chores, possibly at the expense of time that they spend doing schoolwork. Imperfect infrastructure appears to burden the poor in ways that go far beyond obvious health consequences.
</details>

## Book Chapters
Field, Erica, Abraham Holland, and Rohini Pande. "Microfinance: Points of Promise." *Evolving Approaches to the Economics of Public Policy: Views of Award-Winning Economists.* W.E. Upjohn Institute for Employment Research, 2016, 11-32. [https://doi.org/10.17848/9780880995146.ch2](https://doi.org/10.17848/9780880995146.ch2)
<details>
<summary><strong>Abstract</strong></summary>
A majority of the world’s impoverished lack adequate access to financial services. Typically, formal banks do not target the poor because lending without collateral is considered too risky. Poor households seeking credit are subsequently forced into informal markets where the prices are high, the quantities limited, and the methods of insuring repayment can be brutal.

[Full Paper](https://www.dropbox.com/scl/fi/hgll726mcqlunczblta1j/2016_Microfinance-Points-of-Promise_Holland-Field-Pande.pdf?rlkey=6ql9rsp3vb0b8tg2dmc0pyhv7&st=ibg12b9g&dl=0)

Media Coverage: [The Economist](https://www.economist.com/international/2016/10/06/your-inflexible-friend?fsrc=rss%7Cint); [Center for Financial Inclusion](https://www.dropbox.com/scl/fi/kwnap1baims00zxpx6dcl/How-Does-Innovation-Happen.pdf?rlkey=w7hs65ppayqn9exbuedqdwro3&st=3zicd61k&dl=0)
</details>

## Work In-Progress
Holland, R. Abraham, Bishma K. Bhusal, and Prashant Bhandari. *Why Give Up the Ability to Choose? Community Engagement and Surprising Lottery Preferences in Nepal.* Manuscript in progress, to be submitted in 2025. 
<details>
<summary><strong>Abstract</strong></summary>
In theory, individuals should prefer a choice-based lottery (random serial dictatorship) to a uniform random lottery for allocating private goods.  However, data from potential beneficiaries of a Nepalese land allocation program show that almost half of participants prefer uniform random allocation. We observe this fact in both a field laboratory experiment and a randomized high-stakes policy intervention.  In the lab-in-the-field game, participants choose between two lottery mechanisms. By randomizing cash prizes and game anonymity, we test a broad range of explanations.  We find no evidence for lack of comprehension, risk aversion, social pressure, and altruism as potential explanations. At the same time, we find evidence that participants respond, on the margin, to changes in the expected benefits between mechanisms.  In our second experiment, we use an information intervention to influence mechanism preferences outside of a laboratory.   Our findings indicate that information on preference heterogeneity can affect individual mechanism preferences.
</details>
